#PBS -l walltime=08:00:00
#PBS -l nodes=1:ppn=1
#PBS -A PAS1792
#PBS -j oe

cd $PBS_O_WORKDIR

module load vcftools
module load gnu/9.1.0
module load mkl/2019.0.5
module load R/4.0.2

name=`echo ${1} | sed -E 's/.bam$//'`
$HOME/software/bcftools-1.11/bcftools mpileup -f $HOME/sc2/ref/wuhan.fa -d 4000 -q 60 -Q 30 -L 4500 --ff UNMAP,SECONDARY,QCFAIL -a FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,INFO/AD,INFO/ADF,INFO/ADR ${1} | $HOME/software/bcftools-1.11/bcftools call -m -A -Ov -o vcfs/${name}_temp.vcf
$HOME/software/bcftools-1.11/bcftools norm vcfs/${name}_temp.vcf -c w -f $HOME/sc2/ref/wuhan.fa -m -both -Ov -o vcfs/${name}.vcf
vcftools --vcf vcfs/${name}.vcf --site-depth --out depths/${name}
vcftools --vcf vcfs/${name}.vcf --extract-FORMAT-info AD --out AD/${name}

Rscript --verbose $HOME/sc2/scripts/consensus_summary.R ${name} > Rout/${name}.Rout
